// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Vtp29GJC4xEToE8NeyRjuAuK9-fgKKM',
    appId: '1:473755076138:web:d7ac5277a203b82215a553',
    messagingSenderId: '473755076138',
    projectId: 'mybudgettracker-4d6ec',
    authDomain: 'mybudgettracker-4d6ec.firebaseapp.com',
    storageBucket: 'mybudgettracker-4d6ec.appspot.com',
    measurementId: 'G-07TH7F3NP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAekYK_n5HKvJrV5uiIw1qi4Ubt-y8z5TA',
    appId: '1:473755076138:android:544c5900d40d00df15a553',
    messagingSenderId: '473755076138',
    projectId: 'mybudgettracker-4d6ec',
    storageBucket: 'mybudgettracker-4d6ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYccoqelJ5LERTmAR72JpU2yipE_YrAH0',
    appId: '1:473755076138:ios:a6541ff25adb5c1515a553',
    messagingSenderId: '473755076138',
    projectId: 'mybudgettracker-4d6ec',
    storageBucket: 'mybudgettracker-4d6ec.appspot.com',
    iosClientId: '473755076138-s295n4r14shegqmv8ple3769r95ill4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYccoqelJ5LERTmAR72JpU2yipE_YrAH0',
    appId: '1:473755076138:ios:30fe7bdeb6a3988b15a553',
    messagingSenderId: '473755076138',
    projectId: 'mybudgettracker-4d6ec',
    storageBucket: 'mybudgettracker-4d6ec.appspot.com',
    iosClientId: '473755076138-hqnae7u90psjbckd85ig6flb9ln7o9k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
